LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('admin/', admin.site.urls),
    path('portal/', include('academic_portal.urls'), name='portal'),
    path("users/", include("users.urls"), name="users"),
    path("users/", include("django.contrib.auth.urls")),
]

academic_portal/urls.py
from django.urls import path
from academic_portal.views import ChooseCourseView, CourseStudentsView, SuccessView, home, add_course, AssignmentView
app_name = 'academic_portal'

urlpatterns = [
    path('', home, name='home'),
    path('add_course/', add_course, name='add_course'),
    path('assignment/', AssignmentView.as_view(), name='assignment'),
    path('choose_course/', ChooseCourseView.as_view(), name='choose_course'),
    path('attendance_registration/<str:course_code>/', CourseStudentsView.as_view(), name='attendance_registration'),
    path('success/<str:course_code>/', SuccessView.as_view(), name='success_page'),
]

users/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView, logout_view

app_name = "users"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('logout/', logout_view, name='logout'),
]

academic_portal/models.py
from django.db import models
from django.utils.translation import gettext as _
from users.models import CustomUser
from datetime import date

# import choices
from academic_portal.choices import YEAR_OF_STUDY_CHOICES


# Create your models here.
class Lecturer(models.Model):
    user = models.OneToOneField('users.CustomUser', on_delete=models.CASCADE, verbose_name=_('User'),
                                related_name='lecturer')
    courses = models.ManyToManyField('Course', verbose_name=_('Courses'), related_name='lecturers')
    email = models.EmailField(primary_key=True, verbose_name=_('Email'))
    first_name = models.CharField(max_length=50, null=False, blank=False, verbose_name=_('First Name'))
    last_name = models.CharField(max_length=50, null=False, blank=False, verbose_name=_('Last Name'))
    date_of_birth = models.DateField(verbose_name=_('Date of Birth'))

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = _('Lecturer')
        verbose_name_plural = _('Lecturers')
        ordering = ['last_name', 'first_name', 'date_of_birth', 'email']
        indexes = [
            models.Index(fields=['first_name'], name='lecturer_first_name_idx'),
            models.Index(fields=['last_name'], name='lecturer_last_name_idx'),
        ]


class Student(models.Model):
    user = models.OneToOneField('users.CustomUser', on_delete=models.CASCADE, verbose_name=_('User'),
                                related_name='student')
    courses = models.ManyToManyField('Course', verbose_name=_('Courses'), related_name='students')
    faculty = models.ForeignKey('Faculty', on_delete=models.CASCADE, verbose_name=_('Faculty'), related_name='students')
    email = models.EmailField(primary_key=True, verbose_name=_('Email'))
    first_name = models.CharField(max_length=50, null=False, blank=False, verbose_name=_('First Name'))
    last_name = models.CharField(max_length=50, null=False, blank=False, verbose_name=_('Last Name'))
    date_of_birth = models.DateField(verbose_name=_('Date of Birth'))
    year_of_study = models.PositiveSmallIntegerField(choices=YEAR_OF_STUDY_CHOICES, verbose_name=_('Year of Study'))

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = _('Student')
        verbose_name_plural = _('Students')
        ordering = ['last_name', 'first_name', 'date_of_birth', 'email', 'year_of_study', 'faculty']
        indexes = [
            models.Index(fields=['last_name'], name='student_last_name_idx'),
        ]


class Course(models.Model):
    code = models.CharField(max_length=10, primary_key=True, verbose_name=_('Code'))
    title = models.CharField(max_length=100, null=False, blank=False, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    syllabus = models.FileField(upload_to='syllabus/', verbose_name=_('Syllabus'))

    def __str__(self):
        return f'{self.code}'

    class Meta:
        verbose_name = _('Course')
        verbose_name_plural = _('Courses')
        ordering = ['code', 'title']
        indexes = [
            models.Index(fields=['title'], name='course_title_idx'),
        ]


class Faculty(models.Model):
    courses = models.ManyToManyField('Course', verbose_name=_('Courses'), related_name='faculties')
    name = models.CharField(max_length=100, primary_key=True, verbose_name=_('Name'))

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = _('Faculty')
        verbose_name_plural = _('Faculties')


class Assignment(models.Model):
    course = models.ForeignKey('Course', on_delete=models.CASCADE, verbose_name=_('Course'), related_name='assignments')
    title = models.CharField(max_length=100, null=False, blank=False, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    due_date = models.DateTimeField(verbose_name=_('Due Date'))
    file = models.FileField(upload_to='assignments/', verbose_name=_('File'))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = _('Assignment')
        verbose_name_plural = _('Assignments')
        ordering = ['title', 'due_date']
        indexes = [
            models.Index(fields=['title'], name='assignment_title_idx'),
        ]


class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    students_attended = models.ManyToManyField(CustomUser, related_name='attended_courses')
    date = models.DateField(default=date.today)
    
    def __str__(self):
        return f"{self.course.title} - {self.date}"

academic_portal/forms.py
from datetime import date
from django import forms
from academic_portal.models import Assignment, Attendance, Course
from rest_framework import serializers


class AssignmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        lecturer = kwargs.pop('lecturer', None)
        super(AssignmentForm, self).__init__(*args, **kwargs)
        if lecturer:
            self.fields['course'].queryset = lecturer.courses.all()

    class Meta:
        model = Assignment
        fields = ['title', 'description', 'due_date', 'course']
        widgets = {
            'due_date': forms.DateInput(attrs={'type': 'date'}),
        }


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['code', 'title', 'description', 'syllabus']


class AttendanceForm(serializers.ModelSerializer):
    class Meta:
        model = Attendance
        fields = ['date', 'course']

academic_portal/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.db import transaction
from academic_portal.models import Course
from academic_portal.forms import AssignmentForm, AttendanceForm
from users.models import CustomUser
from datetime import date


@login_required
def home(request):
    assignments = []
    if hasattr(request.user, 'lecturer'):
        courses = request.user.lecturer.courses.all()
        for course in courses:
            assignments = assignments + list(course.assignments.all())
    return render(request, 'home1.html', {
        'user': request.user,
        'assignments': assignments
    })


def add_course(request):
    user = request.user
    if user.is_authenticated:
        if request.method == 'POST':
            course = request.POST.get('course')
            course = get_object_or_404(Course, code=course)
            if user.student.courses.filter(code=course.code).exists() or user.student.courses.count() >= 7:
                return redirect('academic_portal:add_course')
            user.student.courses.add(course)
            return redirect('academic_portal:add_course')
        else:
            if hasattr(user, 'student'):
                student = user.student
                return render(request, 'add_course.html', {
                    'courses': student.courses.all(),
                    'first_name': student.first_name,
                    'last_name': student.last_name,
                    'faculty': student.faculty,
                    'all_courses': student.faculty.courses.all()
                })
            else:
                return render(request, 'not_student.html')
    else:
        return redirect('login')


class AssignmentView(View):
    @staticmethod
    def get(request):
        user = request.user
        if user.is_authenticated:
            if hasattr(user, 'student'):
                if hasattr(user, 'student'):
                    form = AssignmentForm()
                    return render(request, 'student_assignment_submission.html', {'form': form})
            elif hasattr(user, 'lecturer'):
                return render(request, 'create_assignment.html', {
                    'form': AssignmentForm(lecturer=user.lecturer)
                })
        else:
            return redirect('login')

    @staticmethod
    def post(request):
        user = request.user
        if user.is_authenticated:
            if hasattr(user, 'student'):
                form = AssignmentForm(request.POST, request.FILES)
                if form.is_valid():
                    form.save()
                    return redirect('academic_portal:home')
                return render(request, 'student_assignment_submission.html', {'form': form})
            elif hasattr(user, 'lecturer'):
                form = AssignmentForm(request.POST)
                if form.is_valid():
                    form.save()
                    return redirect('academic_portal:home')
                return render(request, 'create_assignment.html', {
                    'form': form
                })
        else:
            return redirect('login')


class ChooseCourseView(View):
    @staticmethod
    def get(request):
        if request.user.is_authenticated and hasattr(request.user, 'lecturer'):
            lecturer = request.user.lecturer
            courses = lecturer.courses.all()
            return render(request, 'choose_course.html', {'courses': courses})
        else:
            return redirect('login')


class CourseStudentsView(View):
    @staticmethod
    def get(request, course_code):
        course = Course.objects.get(code=course_code)
        students = course.students.all()
        current_date = date.today()
        form = AttendanceForm()
        return render(request, 'attendance_registration.html',
                      {
                          'form': form,
                          'course': course,
                          'students': students,
                          'current_date': current_date
                      })

    @staticmethod
    def post(request, course_code):
        course = Course.objects.get(code=course_code)
        students = course.students.all()
        current_date = request.POST.get('date', date.today())
        data = request.POST.copy()
        data['course'] = course
        form = AttendanceForm(data=data)
        form.is_valid(raise_exception=True)
        if form.is_valid():
            with transaction.atomic():
                attendance = form.save()
                student_emails = request.POST.getlist('students_attended')

                attended_students = CustomUser.objects.filter(email__in=student_emails)
                for student in attended_students:
                    attendance.students_attended.add(student)
                return render(request, 'success_page.html', {'course': course})
        else:
            return render(request, 'attendance_registration.html',
                          {
                              'form': form,
                              'course': course,
                              'current_date': current_date,
                              'students': students
                          })


class SuccessView(View):
    @staticmethod
    def get(request, course_code):
        course = Course.objects.get(pk=course_code)
        return render(request, 'success_page.html', {'course': course})

academic_portal/templates/add_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 p-4">
    <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
        <div class="p-6">
            <p class="text-lg font-semibold">Hello, {{ first_name }} {{ last_name }}</p>
            <p class="mt-2">You are studying {{ faculty }}</p>
            <p class="mt-2">Here are the courses you are studying:</p>
            <ul class="list-disc pl-4 mt-2">
                {% for course in courses %}
                    <li>{{ course }}</li>
                {% endfor %}
            </ul>

            <p class="mt-4">Take course</p>
            <form action="" method="post" class="mt-2">
                {% csrf_token %}
                <select name="course" class="block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                    {% for course in all_courses %}
                        <option value="{{ course }}">{{ course }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Add course" class="mt-2 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 cursor-pointer">
            </form>
        </div>
    </div>
</body>
</html>

academic_portal/templates/add_course1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <p>Hello, {{ first_name }} {{ last_name }}</p>
        <p>You are studying {{faculty }}</p>
        <p>Here are the courses you are studying:</p>
        <ul>
            {% for course in courses %}
                <li>{{ course }}</li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

academic_portal/templates/attendance_registration.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance</title>
</head>
<body>
    {% block content %}
    <h1 class="text-2xl font-semibold text-center">Mark Attendance for {{ course.title }}</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="course_code" value="{{ course.code }}">
        
        <label for="date">Date:</label>
        <input type="date" id="date" name="date" value="{{ current_date }}" required><br><br>
    
        <h3>Students That Take this Course:</h3>
        {% for student in students %}
        <input type="checkbox" id="student_{{ student.email }}" name="students_attended" value="{{ student.email }}">
        <label for="student_{{ student.email }}">{{ student.first_name }} {{ student.last_name }}</label><br>
        {% endfor %}
        <button type="submit">Submit Attendance</button>
        
    </form>
    {% endblock %}
</body>
</html> 

academic_portal/templates/choose_course.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose Course</title>
</head>
<body>
    {% block content %}
    <h1 class="text-xl font-semibold mb-4">Choose a Course to Register Attendance:</h1>
    <br>
    <div class="container">
      <ul>
        {% for course in courses %}
        <li>
            <a href="{% url 'academic_portal:attendance_registration' course.code %}" >Register Attendance for - {{ course.title }}</a>
        </li>
        {% endfor %}
    </ul>  
    </div>
    {% endblock %}
</body>
</html>

academic_portal/templates/create_assignment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h1 class="text-2xl font-bold mb-4">Upload the assignment</h1>

    <form method="post" class="bg-gray-100 p-4 rounded-lg shadow-md">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Submit</button>
    </form>

</body>
</html>

academic_portal/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Welcome to Academic Portal</h1>
    </header>
    <main>
        <h3>Home Page</h3>
        <p>Welcome to the Academic Portal. Here, you can manage your academic activities.</p>
    </main>
    <br>
    <nav>
        <a href="add_course">Enroll in Courses</a>
    </nav>
    
</body>
</html>

academic_portal/templates/home1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Academic Portal</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <header class="bg-blue-500 text-white py-4 flex justify-between">
        <h1 class="text-2xl font-semibold text-center">Welcome to Academic Portal</h1>
        <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="float-right mr-4 text-white py-2 px-4 rounded">Logout</button>
        </form>
    </header>
    <main class="container mx-auto mt-8 px-4">
        <h3 class="text-xl font-semibold mb-4">Home Page</h3>
        <p class="text-gray-700">Welcome to the Academic Portal. Here, you can manage your academic activities.</p>
    </main>
    <nav class="container mx-auto mt-8 px-4">
        {% if user.lecturer %}
            {% for assignment in assignments %}
                <div class="bg-white p-4 rounded shadow-md mb-4">
                    <h3 class="text-lg font-semibold">{{ assignment.title }}</h3>
                    <p class="text-gray-700">{{ assignment.description }}</p>
                    <p class="text-gray-700">Due Date: {{ assignment.due_date }}</p>
                </div>
            {% endfor %}
            <a href="{% url 'academic_portal:assignment' %}" class="bg-blue-500 text-white py-2 px-4 rounded">Create Assignments</a>
            {% if user.is_authenticated and user.lecturer %}
                <a href="{% url 'academic_portal:choose_course' %}" class="bg-blue-500 text-white py-2 px-4 rounded">Register Attendance for Courses</a>
        {% endif %}
        {% elif user.student %}
            <a href="{% url 'academic_portal:add_course' %}" class="bg-blue-500 text-white py-2 px-4 rounded">Add Courses</a>
            <a href="{% url 'academic_portal:assignment' %}" class="bg-blue-500 text-white py-2 px-4 rounded">Submit Homework</a>
        {% endif %}
    </nav>
</body>
</html>

academic_portal/templates/not_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Hello, {{ first_name }} {{ last_name }}</p>
    <p>You are not a student</p>
    <a href="{% url 'login' %}">Log in with a different account</a>

</body>
</html>

academic_portal/templates/student_assignment_submission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Assignment Submission</title>
</head>
<body>
    <h1>Student Assignment Submission</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Assignment</button>
    </form>
</body>
</html>

academic_portal/templates/success_page.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <form method="post" action="{% url 'academic_portal:success_page' course.code %}">
        {% csrf_token %}
        <main class="text-2xl font-semibold text-center">
            <h2>Attendance Registered Successfully</h2>
            <p>Thank you for marking attendance for {{ course.title }}.</p>
        </main>
        <p><a class="bg-blue-500 text-white py-2 px-4 rounded" href="{% url 'academic_portal:home' %}">Return to Home</a></p>
    </form>
    
        
{% endblock %}
</body>
</html>