LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('admin/', admin.site.urls),
    path('portal/', include('academic_portal.urls'), name='portal'),
    path("users/", include("users.urls"), name="users"),
    path("users/", include("django.contrib.auth.urls")),
]

academic_portal/urls.py
from django.urls import path
from academic_portal.views import ChooseCourseView, CourseStudentsView, SuccessView, home, add_course, AssignmentView
app_name = 'academic_portal'

urlpatterns = [
    path('', home, name='home'),
    path('add_course/', add_course, name='add_course'),
    path('assignment/', AssignmentView.as_view(), name='assignment'),
    path('choose_course/', ChooseCourseView.as_view(), name='choose_course'),
    path('attendance_registration/<str:course_code>/', CourseStudentsView.as_view(), name='attendance_registration'),
    path('success/<str:course_code>/', SuccessView.as_view(), name='success_page'),
]

users/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView, logout_view

app_name = "users"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('logout/', logout_view, name='logout'),
]

templates/base.html
<html>
<head>
  <meta charset="utf-8">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <h1 class="text-3xl font-bold text-center my-8">Learning Management System</h1>

    <div class="flex flex-row gap-3 p-3">
        {% load static %}
        <img src="{% static 'logo.jpg' %}" alt="logo" class="mx-auto w-1/3 aspect-ratio-square">

        <div>
            <p class="mb-4">Welcome to our Learning Management System (LMS) platform! Here, you can easily access
                a variety of courses tailored to your interests and goals. Additionally,
                you can conveniently upload assignments, collaborate with peers,
                and track your progress—all in one place. Start your learning journey
                today and unlock a world of opportunities!
            </p>
            {% if user.is_authenticated %}
              <a href="{% url 'academic_portal:home' %}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Portal</a>

            {% else %}
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-4">
                  <a href="{% url 'login' %}">Log In</a>
                </button>
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                  <a href="{% url 'users:signup' %}">Sign Up</a>
                </button>
            {% endif %}
        </div>

    </div>
{% endblock %}

templates/navbar.html
<nav class="bg-gray-800 text-white p-4 flex justify-between">
        <div>
            <a href="{% url 'home' %}" class="hover:bg-gray-700 px-3 py-2 rounded-md">Home</a>
        </div>
        <div>
            <a href="{% url 'academic_portal:home' %}" class="hover:bg-gray-700 px-3 py-2 rounded-md">Portal</a>
        </div>
        <div>
            <a href="{% url 'users:logout' %}" class="hover:bg-gray-700 px-3 py-2 rounded-md">Logout</a>
        </div>
</nav>